name: PR Check

on:
  pull-request:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      -name:checkout
        uses: actions/checkout@v4
      - name: print branch info
        run: |
          echo "PR opened by: ${{ github.actor }}"
          echo "branch: ${{ github.head_ref }}"
          echo "Target: ${{ github.bese_ref }}"
