name: PR Check

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Print branch info
        run: |
          echo "PR opened by: ${{ github.actor }}"
          echo "Branch: ${{ github.head_ref }}"
          echo "Target: ${{ github.base_ref }}"
